# team:   group 9
# member:
# Zhaoxiang NING, 1261076, Luoyang, China
# Xinyi ZHOU, 1281911, Wuxi, China
# Haochu WANG, 1281962, Nantong, China
# Gengchang XU, 1214774, Zhuhai, China
# Shiming ZHENG, 1149897, Melbourne, Australia
---
# - name: generate bacnkend configuration of couchdb
#   become:
#     yes
#   template:
#     src: couchDBSetting.py.j2
#     dest: '{{remote_working_directory}}/comp90024-project2/backend/couchDBSetting.py'

- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /home/ubuntu/COMP90024/CCC-A2/backend

- name: Start server
  shell: docker-compose up -d --build
  args:
    chdir: /home/ubuntu/COMP90024/CCC-A2/backend

