# team:   group 9
# member:
# Zhaoxiang NING, 1261076, Luoyang, China
# Xinyi ZHOU, 1281911, Wuxi, China
# Haochu WANG, 1281962, Nantong, China
# Gengchang XU, 1214774, Zhuhai, China
# Shiming ZHENG, 1149897, Melbourne, Australia
---
- name: add NectarGroupKey
  copy:
    src: "config/NectarGroupKey.pem"
    dest: ~/.ssh/NectarGroupKey
#    owner: ubuntu
#    group: ubuntu
    mode: 0600