# team:   group 9
# member:
# Zhaoxiang NING, 1261076, Luoyang, China
# Xinyi ZHOU, 1281911, Wuxi, China
# Haochu WANG, 1281962, Nantong, China
# Gengchang XU, 1214774, Zhuhai, China
# Shiming ZHENG, 1149897, Melbourne, Australia
---
- name: Install dependencies
  tags: 'python'
  become: yes
  apt:
    name: ['curl', 'git', 'python3-dev', 'python3-pip', 'python3-setuptools']
    state: latest
    install_recommends: no
    update_cache: yes


- name: Install docker-compose
  tags: 'docker'
  become: yes
  pip:
    name: ['docker']
    state: latest

- name: Shut down previous server
  become:
    yes
  shell: docker-compose down --rmi local
  args:
    chdir: /home/ubuntu/COMP90024/CCC-A2/crawler
#
- name: Start server
  become:
    yes
  shell: docker-compose up  --build -d
  args:
    chdir: /home/ubuntu/COMP90024/CCC-A2/crawler