---
#deploy database and crawler
- hosts: database
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb

- hosts: crawler
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-couchdb-cluster

#deploy frontend
- hosts: frontend
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-frontend

#deploy backend
- hosts: backend
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-backend


- hosts: crawler
  gather_facts: true
  vars_files:
    - host_vars/config.yaml
  roles:
    - role: deploy-crawler
