---
#deploy database and crawler
- hosts: masternode
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-frontend
#     - role: deploy-backend

# - hosts: worker
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-crawler


# - hosts: masternode
#   gather_facts: true
#   vars_files:
#     - host_vars/config.yaml
#   roles:
#     - role: deploy-crawler

# #deploy masternode
# - hosts: backend
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-backend

# #deploy masternode
# - hosts: frontend
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-frontend
