---
#deploy database and crawler
- hosts: backfrontend
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-frontend
    - role: deploy-backend

- hosts: worker
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: deploy-crawler


# - hosts: crawler
#   gather_facts: true
#   vars_files:
#     - host_vars/config.yaml
#   roles:
#     - role: deploy-crawler

# #deploy backend
# - hosts: backend
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-backend

# #deploy frontend
# - hosts: frontend
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-frontend
