---
#deploy frontend and backend
- hosts: masternode
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: git-pull-source-repository
    - role: deploy-frontend
    - role: deploy-backend

# - hosts: worker
#   vars_files:
#     - host_vars/config.yaml
#   gather_facts: true
#   roles:
#     - role: deploy-crawler
