# team:   group 9
# member:
# Zhaoxiang NING, 1261076, Luoyang, China
# Xinyi ZHOU, 1281911, Wuxi, China
# Haochu WANG, 1281962, Nantong, China
# Gengchang XU, 1214774, Zhuhai, China
# Shiming ZHENG, 1149897, Melbourne, Australia
---
#deploy crawler

- hosts: worker
  vars_files:
    - host_vars/config.yaml
  gather_facts: true
  roles:
    - role: git-pull-source-repository
    - role: deploy-crawler
