# team:   group 9
# member:
# Zhaoxiang NING, 1261076, Luoyang, China
# Xinyi ZHOU, 1281911, Wuxi, China
# Haochu WANG, 1281962, Nantong, China
# Gengchang XU, 1214774, Zhuhai, China
# Shiming ZHENG, 1149897, Melbourne, Australia

---
- hosts: localhost
  gather_facts: true

  roles:
    - role: add-NectarGroupKey

- hosts: masternode
  vars_files:
    - host_vars/config.yaml
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
     - role: add-proxy
     - role: install-dependency
     - role: docker-install
     - role: docker-setup 
     - role: docker-network
     - role: docker-image
     - role: docker-create-container
     - role: docker-create-database
     - role: git-clone-source-repository
     - role: mount-volumes
  
- hosts: worker
  vars_files:
    - host_vars/config.yaml
    - host_vars/nectar.yaml
  gather_facts: true

  roles:
    - role: add-proxy
    - role: install-dependency
    - role: docker-install
    - role: docker-setup 
    - role: git-clone-source-repository
    - role: mount-volumes
