---
- name: Check if couchdb is created
  become: yes
  uri:
    url: http://127.0.0.1:5984


- debug:
    msg: "Couchdb is established"



- name: create a database "all_tweets"
  become: yes
  uri:
    url: http://{{couchdb_user}}:{{couchdb_password}}@localhost:5984/all_tweets
    method: PUT
    force_basic_auth: yes
    status_code: 201,412


- debug:
    msg: "A database called all_tweets is created"
